# Generated by Django 5.2 on 2025-04-22 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doktor'), ('patient', 'Hasta')], default='patient', max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_number', models.CharField(max_length=11, unique=True)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A Rh+'), ('A-', 'A Rh-'), ('B+', 'B Rh+'), ('B-', 'B Rh-'), ('AB+', 'AB Rh+'), ('AB-', 'AB Rh-'), ('0+', '0 Rh+'), ('0-', '0 Rh-')], max_length=3, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('chronic_diseases', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('cardiology', 'Kardiyoloji'), ('dermatology', 'Dermatoloji'), ('endocrinology', 'Endokrinoloji'), ('gastroenterology', 'Gastroenteroloji'), ('neurology', 'Nöroloji'), ('oncology', 'Onkoloji'), ('orthopedics', 'Ortopedi'), ('pediatrics', 'Pediatri'), ('psychiatry', 'Psikiyatri'), ('urology', 'Üroloji'), ('general', 'Genel Cerrahi'), ('internal', 'İç Hastalıkları'), ('other', 'Diğer')], max_length=20)),
                ('license_number', models.CharField(max_length=20)),
                ('about', models.TextField(blank=True, null=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='accounts.userprofile')),
            ],
        ),
    ]
