# Generated by Django 5.2 on 2025-04-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_birth_date_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Erkek'), ('female', 'Kadın'), ('other', 'Diğer')], default='other', max_length=10),
        ),
    ]
